-- 코드를 작성해주세요
SELECT ROUND(AVG(UN.LENGTH),2) AS AVERAGE_LENGTH
FROM   (SELECT *
        FROM FISH_INFO
        UNION 
        SELECT ID, FISH_TYPE, IFNULL(LENGTH,10) AS LENGTH, TIME
        FROM FISH_INFO
        WHERE LENGTH IS NULL) UN
;