-- 코드를 입력하세요
# DATEDIFF(date1,date2) -> 두 날짜의 차이 
SELECT CAR_ID, ROUND(AVG(DATEDIFF(end_date,start_date)+1),1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC