SELECT DATE_FORMAT(OS.SALES_DATE, '%Y') AS YEAR,
        DATE_FORMAT(OS.SALES_DATE, '%m') AS MONTH,
        COUNT(DISTINCT UI.USER_ID) AS PUCHASED_USERS,
        ROUND(COUNT(DISTINCT UI.USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE joined LIKE '2021%'), 1) AS PUCHASED_RATIO
FROM USER_INFO UI ,ONLINE_SALE OS
WHERE UI.USER_ID = OS.USER_ID
AND UI.JOINED LIKE '2021%'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH
;