WITH RECURSIVE CTE 
AS (
    -- Non-Recursive 문장(첫번째 루프에서만 실행)
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL -- 부모가 없는 1세대
    UNION ALL
    
    -- Recursive 문장(읽어올때마다 실행됨)
    SELECT A.ID, GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA A 
    LEFT JOIN CTE B ON A.PARENT_ID = B.ID
    WHERE A.PARENT_ID = B.ID -- 정지 조건
)

SELECT COUNT(*) COUNT, GENERATION 
FROM CTE AS A
WHERE NOT EXISTS(SELECT 1 FROM ECOLI_DATA WHERE PARENT_ID = A.ID)
GROUP BY GENERATION;