SELECT MR.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE MR 
JOIN REST_REVIEW RR
ON MR.MEMBER_ID = RR.MEMBER_ID
WHERE RR.MEMBER_ID = (SELECT RR.MEMBER_ID
                      FROM REST_REVIEW RR
                      GROUP BY RR.MEMBER_ID
                      ORDER BY COUNT(*) DESC
                      LIMIT 1)
ORDER BY REVIEW_DATE, RR.REVIEW_TEXT;